In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt  # Corrected import statement
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

df = pd.read_csv('data/b_data.csv')

df.head(10)

,first_name,last_name,sector,salary,agreeableness,conscientiousness,extroversion,neuroticism,openness
0,Kelsi,Pottberry,hospitality,101-150,2,2,3,2,2
1,Cassey,Rowbrey,hospitality,101-150,3,1,3,1,1
2,Jed,Mullett,hospitality,101-150,2,3,2,2,3
3,Fidelity,Shuttleworth,finance,101-150,3,2,1,2,1
4,Rhodie,Fencott,hospitality,51-100,3,1,1,1,2
5,Anissa,Niessen,healthcare,101-150,3,3,1,2,2
6,Gottfried,Meeks,entertainment,50,2,1,1,2,1
7,Ker,Ghidotti,marketing,50,1,3,3,2,2
8,Meyer,Fenlon,marketing,50,1,2,3,2,2
9,Waverly,Gommes,entertainment,151-250,3,2,3,3,1

In [9]:
# Scatter plot
plt.figure(figsize=(10, 6))
sns.scatterplot(x='agreeableness', y='salary_range', hue='sector', data=df, palette='viridis')

# Customize plot
plt.title('Scatter Plot of Agreeableness vs Salary Range')
plt.xlabel('Agreeableness')
plt.ylabel('Salary Range')
plt.legend(title='Sector')

# Show the plot
plt.show()

ValueError: Could not interpret value `salary_range` for parameter `y`